#!/usr/bin/env php
<?php
#ddev-generated

# internal
# experimenting with editing the phpunit.xml file as xml rather than
# using token replacement.
# this means we can edit what's in place rather than always copying a template.

$composer_root = getenv('DDEV_COMPOSER_ROOT');
$doc_root = getenv('DDEV_DOCROOT');
$loader = require_once $composer_root . '/' . $doc_root . '/autoload.php';

$options = getopt('', [
  'database:',
  'browser:',
]);

if (isset($options['database'])) {
  $doc = new \DOMDocument();
  $doc->load('phpunit.xml');

  $db_url = match ($options['database']) {
    'sqlite'    => 'sqlite://localhost/sites/default/files/db.sqlite',
    'mysql'     => 'mysql://db:db@db/db',
    'postgres'  => 'pgsql://db:db@db/db',
  };

  // Set the value of this node:
  // <env name="SIMPLETEST_DB" value="SIMPLETEST_DB_VALUE"/>
  $xpath = new \DOMXpath($doc);
  $node_list = $xpath->query("//phpunit/php/env[@name='SIMPLETEST_DB']");
  if (empty($node_list)) {
    throw new \Exception("Unable to find SIMPLETEST_DB env node.");
  }

  $node = $node_list[0];
  $node->setAttribute('value', $db_url);

  $doc->save('phpunit.xml');
}

if (isset($options['browser'])) {
  // Copy the values from this XML extract into the matching elements.
  $browser_xml_snippet_file = ".ddev/core-dev/phpunit-snippet-{$options['browser']}.xml";
  $browser_xml_snippet = file_get_contents($browser_xml_snippet_file);

  // Trim out the XML comment.
  $browser_xml_snippet = preg_replace("/<!--.*-->\n/s", '', $browser_xml_snippet);

  $phpunit_file = file_get_contents('phpunit.xml');
  dump($phpunit_file);
  $phpunit_file = preg_replace("/(?<=<!-- MINK_DRIVER_INSERT_START -->\n).+\n(?=\s+<!-- MINK_DRIVER_INSERT_END -->)/ms", $browser_xml_snippet, $phpunit_file);
  file_put_contents('phpunit.xml', $phpunit_file);
}

