#!/usr/bin/env php

#ddev-generated

<?php

$doc = new \DOMDocument();
$doc->load('phpunit.xml');

# cp .ddev/core-dev/phpunit-chrome.xml phpunit.xml
# perl -pi -e "s|DRUPAL_CORE_DDEV_URL|$DDEV_PRIMARY_URL|g" phpunit.xml
# perl -pi -e "'$DDEV_DOCROOT' and s|DDEV_DOCROOT|$DDEV_DOCROOT/|g" phpunit.xml
