#!/usr/bin/env php
<?php
#ddev-generated

# internal
# experimenting with editing the phpunit.xml file as xml rather than
# using token replacement.
# this means we can edit what's in place rather than always copying a template.

$composer_root = getenv('DDEV_COMPOSER_ROOT');
$doc_root = getenv('DDEV_DOCROOT');
$loader = require_once $composer_root . '/' . $doc_root . '/autoload.php';

$options = getopt('', [
  'database:',
  'browser:',
]);

// dump($options);

$doc = new \DOMDocument();
$doc->load('phpunit.xml');
$save = FALSE;

if (isset($options['database'])) {
  $db_url = match ($options['database']) {
    'sqlite'    => 'sqlite://localhost/sites/default/files/db.sqlite',
    'mysql'     => 'mysql://db:db@db/db',
    'postgres'  => 'pgsql://db:db@db/db',
  };

  // Set the value of this node:
  // <env name="SIMPLETEST_DB" value="SIMPLETEST_DB_VALUE"/>
  $xpath = new \DOMXpath($doc);
  $node_list = $xpath->query("//phpunit/php/env[@name='SIMPLETEST_DB']");
  if (empty($node_list)) {
    throw new \Exception("Unable to find SIMPLETEST_DB env node.");
  }

  $node = $node_list[0];
  $node->setAttribute('value', $db_url);

  $save = TRUE;
}

if (isset($options['browser'])) {
  // Copy the values from this XML extract into the matching elements.
  $browser_xml = match($options['browser']) {
    'chrome' => <<<EOXML
      <php>
        <env name="MINK_DRIVER_ARGS" value='["chrome", {"browserName":"chrome", "goog:chromeOptions":{"args":["--no-sandbox","--ignore-certificate-errors", "--allow-insecure-localhost"]}}, "http://chrome:4444"]'/>
        <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["chrome", {"browserName":"chrome", "goog:chromeOptions":{"args":["--no-sandbox","--ignore-certificate-errors", "--allow-insecure-localhost"]}}, "http://chrome:4444"]'/>
      </php>
      EOXML,
    'firefox' => <<<EOXML
      <php>
        <env name="MINK_DRIVER_ARGS" value='["firefox", {"browserName":"firefox", "moz:firefoxOptions":{"args":[]}}, "http://firefox:4444"]'/>
        <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["firefox", {"browserName":"firefox", "moz:firefoxOptions":{"args":[]}}, "http://firefox:4444"]'/>
      </php>
      EOXML,
  };

  $insert = new \DOMDocument();
  $insert->loadXML($browser_xml);
  $xpath = new \DOMXpath($insert);
  $node_list = $xpath->query("//php/env");
  foreach ($node_list as $insert_env_node) {
    $env_name = $insert_env_node->getAttribute('name');

    $xpath = new \DOMXpath($doc);
    $node_list = $xpath->query("//phpunit/php/env[@name='{$env_name}']");
    if (empty($node_list)) {
      throw new \Exception("Unable to find '{$env_name}' env node.");
    }

    dump($insert_env_node->getAttribute('value'));


    $node = $node_list[0];
    $node->setAttribute('value', urldecode($insert_env_node->getAttribute('value')));
    # AAAARGH QUOTESS!
    # $node->setAttribute('value', '"aaaargh," he said');

    # $imported = $doc->importNode($insert_env_node);
    # $node->appendChild($imported);

  }

  $save = TRUE;
}

if ($save) {
  $doc->save('phpunit.xml');
}
