#!/bin/bash

#ddev-generated

## Description: Run phpstan
## Usage: phpstan [flags] [args]
## Example: "ddev phpstan core/modules/migrate_drupal_ui"

TOP_LEVEL="/var/www/html/repos/drupal"
cd $TOP_LEVEL

if ! command -v /var/www/html/vendor/bin/phpstan >/dev/null; then
  echo "phpstan is not in PATH in the web container. You probably forgot to 'ddev composer install'"
  exit 2
fi

/var/www/html/vendor/bin/phpstan analyze  --configuration="$TOP_LEVEL/core/phpstan.neon.dist" --xdebug --no-ansi --memory-limit=2G $@ || \
echo "Return code ignored"
