#!/bin/bash

#ddev-generated

## Description: Clean up test results
## Usage: tests-cleanup
## Example: "ddev tests-cleanup"

TOP_LEVEL="/var/www/html"
cd $TOP_LEVEL

if [ ! -d "./test_output" ]
then
  echo "The expected folder test_output does not exist."
  exit 2
fi

rm ./test_output/*.counter
rm ./test_output/*.html

echo "Test files removed."
